### ISSUE TITLE
课时10Convolution Network

### ISSUE THREAD

**Issue by smallhaes** [yule-li/tensorflow-practice#1]
老师，在Convolution Network这一课中，为什么用image = tf.constant(np.random.normal(size=[1,112,96,3]),dtype=tf.float32)训练时pred_np可以无限接近于1

**Comment by yule-li** [comment]
When you use ```image = tf.constant(np.random.normal(size=[1,112,96,3]),dtype=tf.float32)```, the value of tensor ```image``` is fixed after initialization, so the parameters of model can fit the ```image => 1```. However, if you use ```image = tf.random_normal([1,112,96,3])```, the value of tensor ```image``` will be different every time you run the model, so it's hard to fit ```image=>1```.

**Comment by smallhaes** [comment]
谢谢老师！

**Comment by smallhaes** [comment]
谢谢老师！
